# Generated by Django 5.2.17 on 2026-10-02 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# RoleEvent is append-only (docs/DATA_MODEL.md §3.1, rule I-1). The trigger is
# created together with the table, so the table never exists unprotected. It
# refuses UPDATE and DELETE on every row, for every database role, whatever
# sent the statement.
#
# What it does not cover, and what the production database role must therefore
# not be able to do (ADR-0002, least-privilege roles): TRUNCATE, which fires no
# row trigger, and dropping or disabling the trigger, which needs ownership of
# the table.
CREATE_APPEND_ONLY_TRIGGER = """
CREATE FUNCTION accounts_roleevent_refuse_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'accounts_roleevent is append-only: % refused', TG_OP
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$;

CREATE TRIGGER accounts_roleevent_append_only
    BEFORE UPDATE OR DELETE ON accounts_roleevent
    FOR EACH ROW EXECUTE FUNCTION accounts_roleevent_refuse_change();
"""

DROP_APPEND_ONLY_TRIGGER = """
DROP TRIGGER accounts_roleevent_append_only ON accounts_roleevent;
DROP FUNCTION accounts_roleevent_refuse_change();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("reader", "Reader"),
                            ("researcher", "Researcher"),
                            ("reviewer", "Reviewer"),
                            ("administrator", "Administrator"),
                        ],
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("granted", "Granted"), ("revoked", "Revoked")],
                        max_length=10,
                        verbose_name="event type",
                    ),
                ),
                ("reason", models.TextField(verbose_name="reason")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "role event",
                "verbose_name_plural": "role events",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("role__in", ["reader", "researcher", "reviewer", "administrator"])
                        ),
                        name="accounts_roleevent_role_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("event_type__in", ["granted", "revoked"])),
                        name="accounts_roleevent_event_type_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason", ""), _negated=True),
                        name="accounts_roleevent_reason_given",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("actor", models.F("user")), _negated=True),
                        name="accounts_roleevent_actor_is_not_user",
                    ),
                ],
            },
        ),
        migrations.RunSQL(sql=CREATE_APPEND_ONLY_TRIGGER, reverse_sql=DROP_APPEND_ONLY_TRIGGER),
    ]
