# Generated by Django 5.2.17 on 2026-10-02 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# AuthenticationEvent is append-only, protected in the same way as RoleEvent
# (ADR-0012, migration 0002): a trigger created with the table refuses UPDATE
# and DELETE on every row, for every database role. The same limits apply:
# TRUNCATE, and dropping or disabling the trigger, are matters of database
# privilege.
CREATE_APPEND_ONLY_TRIGGER = """
CREATE FUNCTION accounts_authenticationevent_refuse_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'accounts_authenticationevent is append-only: % refused', TG_OP
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$;

CREATE TRIGGER accounts_authenticationevent_append_only
    BEFORE UPDATE OR DELETE ON accounts_authenticationevent
    FOR EACH ROW EXECUTE FUNCTION accounts_authenticationevent_refuse_change();
"""

DROP_APPEND_ONLY_TRIGGER = """
DROP TRIGGER accounts_authenticationevent_append_only ON accounts_authenticationevent;
DROP FUNCTION accounts_authenticationevent_refuse_change();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_role_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Signed in"),
                            ("login_failure", "Sign-in failed"),
                            ("logout", "Signed out"),
                        ],
                        max_length=20,
                        verbose_name="event type",
                    ),
                ),
                ("identifier_key", models.CharField(max_length=64, verbose_name="identifier key")),
                ("source_key", models.CharField(max_length=64, verbose_name="source key")),
                (
                    "correlation_id",
                    models.CharField(blank=True, max_length=32, verbose_name="correlation ID"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
            ],
            options={
                "verbose_name": "authentication event",
                "verbose_name_plural": "authentication events",
            },
        ),
        migrations.AlterField(
            model_name="roleevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="actor",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actor__isnull", False),
                    models.Q(("event_type", "granted"), ("role", "administrator")),
                    _connector="OR",
                ),
                name="accounts_roleevent_no_actor_only_for_bootstrap",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("actor__isnull", True)),
                fields=("event_type",),
                name="accounts_roleevent_single_bootstrap",
            ),
        ),
        migrations.AddField(
            model_name="authenticationevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="authenticationevent",
            index=models.Index(
                fields=["identifier_key", "created_at"], name="accounts_authevent_identifier"
            ),
        ),
        migrations.AddIndex(
            model_name="authenticationevent",
            index=models.Index(
                fields=["source_key", "created_at"], name="accounts_authevent_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="authenticationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("event_type__in", ["login_success", "login_failure", "logout"])
                ),
                name="accounts_authenticationevent_event_type_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="authenticationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False), ("event_type", "login_failure"), _connector="OR"
                ),
                name="accounts_authenticationevent_user_known_unless_failure",
            ),
        ),
        migrations.RunSQL(sql=CREATE_APPEND_ONLY_TRIGGER, reverse_sql=DROP_APPEND_ONLY_TRIGGER),
    ]
