# Generated by Django 5.2.17 on 2026-10-02 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# AuthenticationEvent is append-only, and a trigger refuses UPDATE and DELETE
# on its rows (migration 0003). The two changes made to it here touch no row:
# widening the event type column changes only the column's declared length,
# and replacing the check constraint validates the existing rows, all of which
# hold one of the three earlier event types. Reversing this migration while
# rows with the new event types exist fails on the restored constraint, which
# is intended: those rows must not be altered or removed to make it fit.


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_authentication"),
    ]

    operations = [
        migrations.CreateModel(
            name="MfaChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token_key",
                    models.CharField(max_length=64, unique=True, verbose_name="token key"),
                ),
                ("created_at", models.DateTimeField(verbose_name="created at")),
            ],
            options={
                "verbose_name": "second-factor challenge",
                "verbose_name_plural": "second-factor challenges",
            },
        ),
        migrations.CreateModel(
            name="TotpDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("pending", "Enrolment pending"), ("active", "Active")],
                        max_length=10,
                        verbose_name="state",
                    ),
                ),
                ("secret_ciphertext", models.BinaryField(verbose_name="encrypted secret")),
                (
                    "key_id",
                    models.CharField(max_length=16, verbose_name="encryption key identifier"),
                ),
                (
                    "last_used_step",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="last used time step"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "confirmed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="confirmed at"),
                ),
            ],
            options={
                "verbose_name": "TOTP device",
                "verbose_name_plural": "TOTP devices",
            },
        ),
        migrations.RemoveConstraint(
            model_name="authenticationevent",
            name="accounts_authenticationevent_event_type_known",
        ),
        migrations.AlterField(
            model_name="authenticationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_success", "Signed in"),
                    ("login_failure", "Sign-in failed"),
                    ("logout", "Signed out"),
                    ("password_confirmation_failed", "Password not confirmed"),
                    ("mfa_challenge_issued", "Second factor requested"),
                    ("mfa_enrollment_started", "Second-factor enrolment started"),
                    ("mfa_enrollment_succeeded", "Second factor enrolled"),
                    ("mfa_verification_failed", "Second-factor code refused"),
                    ("mfa_verification_succeeded", "Second-factor code accepted"),
                    ("mfa_disabled", "Second factor disabled"),
                ],
                max_length=32,
                verbose_name="event type",
            ),
        ),
        migrations.AddConstraint(
            model_name="authenticationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event_type__in",
                        [
                            "login_success",
                            "login_failure",
                            "logout",
                            "password_confirmation_failed",
                            "mfa_challenge_issued",
                            "mfa_enrollment_started",
                            "mfa_enrollment_succeeded",
                            "mfa_verification_failed",
                            "mfa_verification_succeeded",
                            "mfa_disabled",
                        ],
                    )
                ),
                name="accounts_authenticationevent_event_type_known",
            ),
        ),
        migrations.AddField(
            model_name="mfachallenge",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="totpdevice",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddConstraint(
            model_name="totpdevice",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["pending", "active"])),
                name="accounts_totpdevice_state_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="totpdevice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("confirmed_at__isnull", True),
                        ("last_used_step__isnull", True),
                        ("state", "pending"),
                    ),
                    models.Q(
                        ("confirmed_at__isnull", False),
                        ("last_used_step__isnull", False),
                        ("state", "active"),
                    ),
                    _connector="OR",
                ),
                name="accounts_totpdevice_active_iff_confirmed",
            ),
        ),
    ]
