# Generated by Django 5.2.17 on 2026-10-03 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Second-factor enrolment gains an approval step (ADR-0014, as amended).
#
# AuthenticationEvent is append-only, and a trigger refuses UPDATE and DELETE
# on its rows (migration 0003). What is done to it here touches no row: a
# nullable column is added, and the check constraints are replaced after
# validating the existing rows, none of which names an actor or holds one of
# the three new event types. Reversing this migration while rows with the new
# event types exist fails on the restored constraint, which is intended, and
# reversing it drops the record of who approved or rejected a request.
#
# TotpDevice is operational state. The one earlier pending state is renamed:
# it always meant "awaiting the first code". Existing active devices are left
# as they are, which is unapproved: they were enrolled on a password alone,
# and no migration may declare them trusted. An account whose roles require a
# second factor replaces such a device and has the new one approved. A
# database whose only Administrator enrolled before this migration has nobody
# who could approve; it is recreated (docs/DEVELOPMENT.md). No deployment
# exists that this could affect. Reversing removes requests that await
# approval, which the earlier schema cannot represent.


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_second_factor"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="authenticationevent",
            name="accounts_authenticationevent_event_type_known",
        ),
        migrations.RemoveConstraint(
            model_name="totpdevice",
            name="accounts_totpdevice_state_known",
        ),
        migrations.RemoveConstraint(
            model_name="totpdevice",
            name="accounts_totpdevice_active_iff_confirmed",
        ),
        migrations.AddField(
            model_name="authenticationevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="actor",
            ),
        ),
        migrations.AddField(
            model_name="totpdevice",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="approved at"),
        ),
        migrations.AddField(
            model_name="totpdevice",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="approved by",
            ),
        ),
        migrations.AlterField(
            model_name="authenticationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_success", "Signed in"),
                    ("login_failure", "Sign-in failed"),
                    ("logout", "Signed out"),
                    ("password_confirmation_failed", "Password not confirmed"),
                    ("mfa_challenge_issued", "Second factor requested"),
                    ("mfa_enrollment_started", "Second-factor enrolment started"),
                    ("mfa_enrollment_succeeded", "Second factor enrolled"),
                    ("mfa_verification_failed", "Second-factor code refused"),
                    ("mfa_verification_succeeded", "Second-factor code accepted"),
                    ("mfa_disabled", "Second factor disabled"),
                    ("mfa_enrollment_approved", "Second-factor enrolment approved"),
                    ("mfa_enrollment_rejected", "Second-factor enrolment rejected"),
                    ("mfa_device_replaced", "Second factor replaced"),
                ],
                max_length=32,
                verbose_name="event type",
            ),
        ),
        migrations.AlterField(
            model_name="totpdevice",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Awaiting approval"),
                    ("pending_verification", "Awaiting verification"),
                    ("active", "Active"),
                ],
                max_length=20,
                verbose_name="state",
            ),
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE accounts_totpdevice SET state = 'pending_verification'"
                " WHERE state = 'pending'"
            ),
            reverse_sql=[
                "DELETE FROM accounts_totpdevice WHERE state = 'pending_approval'",
                "UPDATE accounts_totpdevice SET state = 'pending'"
                " WHERE state = 'pending_verification'",
            ],
        ),
        migrations.AddConstraint(
            model_name="authenticationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event_type__in",
                        [
                            "login_success",
                            "login_failure",
                            "logout",
                            "password_confirmation_failed",
                            "mfa_challenge_issued",
                            "mfa_enrollment_started",
                            "mfa_enrollment_succeeded",
                            "mfa_verification_failed",
                            "mfa_verification_succeeded",
                            "mfa_disabled",
                            "mfa_enrollment_approved",
                            "mfa_enrollment_rejected",
                            "mfa_device_replaced",
                        ],
                    )
                ),
                name="accounts_authenticationevent_event_type_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="authenticationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("actor__isnull", False),
                        ("event_type__in", ("mfa_enrollment_approved", "mfa_enrollment_rejected")),
                    ),
                    models.Q(
                        ("actor__isnull", True),
                        models.Q(
                            (
                                "event_type__in",
                                ("mfa_enrollment_approved", "mfa_enrollment_rejected"),
                            ),
                            _negated=True,
                        ),
                    ),
                    _connector="OR",
                ),
                name="accounts_authenticationevent_actor_iff_decision",
            ),
        ),
        migrations.AddConstraint(
            model_name="authenticationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("actor", models.F("user")), _negated=True),
                name="accounts_authenticationevent_actor_is_not_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="totpdevice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["pending_approval", "pending_verification", "active"])
                ),
                name="accounts_totpdevice_state_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="totpdevice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("confirmed_at__isnull", True),
                        ("last_used_step__isnull", True),
                        ("state__in", ["pending_approval", "pending_verification"]),
                    ),
                    models.Q(
                        ("confirmed_at__isnull", False),
                        ("last_used_step__isnull", False),
                        ("state", "active"),
                    ),
                    _connector="OR",
                ),
                name="accounts_totpdevice_active_iff_confirmed",
            ),
        ),
        migrations.AddConstraint(
            model_name="totpdevice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "pending_approval"), _negated=True),
                    ("approved_at__isnull", True),
                    _connector="OR",
                ),
                name="accounts_totpdevice_awaiting_approval_is_unapproved",
            ),
        ),
        migrations.AddConstraint(
            model_name="totpdevice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_by__isnull", True),
                    models.Q(
                        ("approved_at__isnull", False),
                        models.Q(("approved_by", models.F("user")), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="accounts_totpdevice_approver_is_not_user",
            ),
        ),
    ]
