# Generated by Django 5.2.17 on 2026-10-03 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# The account lifecycle (ADR-0015).
#
# The stored flag `is_active` is replaced by `status`. Every account that
# exists was created active, by the first-Administrator bootstrap, and was
# either left so or deactivated. So an account whose flag is set becomes
# `active`, one whose flag is not becomes `disabled`, and each records the
# time it was created as the time it became active. No account is marked as
# having a verified email address: none was verified. Reversing restores the
# flag from the status; an account that awaits verification, which the earlier
# schema cannot represent, comes back as not active.
#
# AccountEvent is append-only, protected in the same way as RoleEvent and
# AuthenticationEvent (ADR-0012, migrations 0002 and 0003): a trigger created
# with the table refuses UPDATE and DELETE on every row, for every database
# role. The same limits apply: TRUNCATE, and dropping or disabling the
# trigger, are matters of database privilege.
CREATE_APPEND_ONLY_TRIGGER = """
CREATE FUNCTION accounts_accountevent_refuse_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'accounts_accountevent is append-only: % refused', TG_OP
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$;

CREATE TRIGGER accounts_accountevent_append_only
    BEFORE UPDATE OR DELETE ON accounts_accountevent
    FOR EACH ROW EXECUTE FUNCTION accounts_accountevent_refuse_change();
"""

DROP_APPEND_ONLY_TRIGGER = """
DROP TRIGGER accounts_accountevent_append_only ON accounts_accountevent;
DROP FUNCTION accounts_accountevent_refuse_change();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_second_factor_approval"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token_key",
                    models.CharField(max_length=64, unique=True, verbose_name="token key"),
                ),
                ("created_at", models.DateTimeField(verbose_name="created at")),
            ],
            options={
                "verbose_name": "account activation",
                "verbose_name_plural": "account activations",
            },
        ),
        migrations.CreateModel(
            name="AccountEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("account_created", "Account created"),
                            ("verification_sent", "Verification message sent"),
                            ("verification_succeeded", "Email address verified"),
                            ("verification_failed", "Verification refused"),
                            ("account_disabled", "Account disabled"),
                            ("account_enabled", "Account enabled"),
                        ],
                        max_length=32,
                        verbose_name="event type",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(blank=True, max_length=64, verbose_name="source key"),
                ),
                (
                    "correlation_id",
                    models.CharField(blank=True, max_length=32, verbose_name="correlation ID"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
            ],
            options={
                "verbose_name": "account event",
                "verbose_name_plural": "account events",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_verification", "Awaiting verification"),
                    ("active", "Active"),
                    ("disabled", "Disabled"),
                ],
                default="active",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="activated at"),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="email verified at"),
        ),
        migrations.RunSQL(
            sql=[
                "UPDATE accounts_user SET status = 'disabled' WHERE NOT is_active",
                "UPDATE accounts_user SET activated_at = created_at",
            ],
            reverse_sql="UPDATE accounts_user SET is_active = (status = 'active')",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_verification", "Awaiting verification"),
                    ("active", "Active"),
                    ("disabled", "Disabled"),
                ],
                default="pending_verification",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending_verification", "active", "disabled"])),
                name="accounts_user_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("activated_at__isnull", True),
                        ("email_verified_at__isnull", True),
                        ("status", "pending_verification"),
                    ),
                    models.Q(("activated_at__isnull", False), ("status", "active")),
                    ("status", "disabled"),
                    _connector="OR",
                ),
                name="accounts_user_status_matches_history",
            ),
        ),
        migrations.AddField(
            model_name="accountactivation",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="accountevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="actor",
            ),
        ),
        migrations.AddField(
            model_name="accountevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="accountevent",
            index=models.Index(
                fields=["source_key", "created_at"], name="accounts_acctevent_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event_type__in",
                        [
                            "account_created",
                            "verification_sent",
                            "verification_succeeded",
                            "verification_failed",
                            "account_disabled",
                            "account_enabled",
                        ],
                    )
                ),
                name="accounts_accountevent_event_type_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False), ("event_type", "verification_failed"), _connector="OR"
                ),
                name="accounts_accountevent_user_known_unless_failure",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("actor__isnull", False),
                        (
                            "event_type__in",
                            (
                                "account_created",
                                "verification_sent",
                                "account_disabled",
                                "account_enabled",
                            ),
                        ),
                    ),
                    models.Q(
                        ("actor__isnull", True),
                        models.Q(
                            (
                                "event_type__in",
                                (
                                    "account_created",
                                    "verification_sent",
                                    "account_disabled",
                                    "account_enabled",
                                ),
                            ),
                            _negated=True,
                        ),
                    ),
                    _connector="OR",
                ),
                name="accounts_accountevent_actor_iff_administrative",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("actor", models.F("user")), _negated=True),
                    ("event_type", "account_disabled"),
                    _connector="OR",
                ),
                name="accounts_accountevent_actor_is_not_user_unless_disabling",
            ),
        ),
        migrations.RunSQL(sql=CREATE_APPEND_ONLY_TRIGGER, reverse_sql=DROP_APPEND_ONLY_TRIGGER),
    ]
