# Generated by Django 5.2.17 on 2026-10-03 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Password reset by email (ADR-0016).
#
# PasswordReset is operational state, like AccountActivation: one row for an
# account that has an outstanding reset token, holding the token's keyed hash
# and the time it lapses.
#
# AuthenticationEvent is append-only, and a trigger refuses UPDATE and DELETE
# on its rows (migration 0003). What is done to it here touches no row: two
# check constraints are replaced after validating the existing rows, none of
# which holds one of the three new event types, and only a failed sign-in
# among them names no user. The constraint that only a failed sign-in may name
# no user now also allows a reset request and a refused reset. Every other
# constraint, the indexes, and the trigger are left as they are.
#
# Reversing drops the PasswordReset table, and with it any outstanding token.
# Reversing while rows with the new event types exist fails on the restored
# constraints, which is intended: those rows cannot be removed, and the
# earlier schema cannot represent them.


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_account_lifecycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token_key",
                    models.CharField(max_length=64, unique=True, verbose_name="token key"),
                ),
                ("created_at", models.DateTimeField(verbose_name="created at")),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
            ],
            options={
                "verbose_name": "password reset",
                "verbose_name_plural": "password resets",
            },
        ),
        migrations.RemoveConstraint(
            model_name="authenticationevent",
            name="accounts_authenticationevent_user_known_unless_failure",
        ),
        migrations.RemoveConstraint(
            model_name="authenticationevent",
            name="accounts_authenticationevent_event_type_known",
        ),
        migrations.AlterField(
            model_name="authenticationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_success", "Signed in"),
                    ("login_failure", "Sign-in failed"),
                    ("logout", "Signed out"),
                    ("password_confirmation_failed", "Password not confirmed"),
                    ("mfa_challenge_issued", "Second factor requested"),
                    ("mfa_enrollment_started", "Second-factor enrolment started"),
                    ("mfa_enrollment_succeeded", "Second factor enrolled"),
                    ("mfa_verification_failed", "Second-factor code refused"),
                    ("mfa_verification_succeeded", "Second-factor code accepted"),
                    ("mfa_disabled", "Second factor disabled"),
                    ("mfa_enrollment_approved", "Second-factor enrolment approved"),
                    ("mfa_enrollment_rejected", "Second-factor enrolment rejected"),
                    ("mfa_device_replaced", "Second factor replaced"),
                    ("password_reset_requested", "Password reset requested"),
                    ("password_reset_succeeded", "Password reset"),
                    ("password_reset_failed", "Password reset refused"),
                ],
                max_length=32,
                verbose_name="event type",
            ),
        ),
        migrations.AddConstraint(
            model_name="authenticationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event_type__in",
                        [
                            "login_success",
                            "login_failure",
                            "logout",
                            "password_confirmation_failed",
                            "mfa_challenge_issued",
                            "mfa_enrollment_started",
                            "mfa_enrollment_succeeded",
                            "mfa_verification_failed",
                            "mfa_verification_succeeded",
                            "mfa_disabled",
                            "mfa_enrollment_approved",
                            "mfa_enrollment_rejected",
                            "mfa_device_replaced",
                            "password_reset_requested",
                            "password_reset_succeeded",
                            "password_reset_failed",
                        ],
                    )
                ),
                name="accounts_authenticationevent_event_type_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="authenticationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False),
                    (
                        "event_type__in",
                        ("login_failure", "password_reset_requested", "password_reset_failed"),
                    ),
                    _connector="OR",
                ),
                name="accounts_authenticationevent_user_known_unless_failure",
            ),
        ),
        migrations.AddField(
            model_name="passwordreset",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddConstraint(
            model_name="passwordreset",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("created_at"))),
                name="accounts_passwordreset_expires_after_created",
            ),
        ),
    ]
