# Generated by Django 5.2.17 on 2026-10-05 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# The schema that recovery of a lost second factor needs (ADR-0017). Nothing
# here recovers anything: no service, page, or command uses it yet.
#
# MfaRecoveryRequest is operational state, like MfaChallenge: one row for an
# account whose owner asked for recovery. Its identifier is the number of the
# request.
#
# User gains session_epoch. Every existing account gets 0, and at 0 a session
# is recognised exactly as before, so applying this migration signs nobody
# out.
#
# AuthenticationEvent is append-only, and a trigger refuses UPDATE and DELETE
# on its rows (migration 0003). What is done to it here touches no row: a
# column that is empty on every existing row is added, and three check
# constraints are replaced after validating the existing rows, none of which
# holds one of the six new event types. The constraint on which events may
# name no user now also allows a refused recovery submission, and the one on
# which events name an actor now also covers a rejected and an authorised
# recovery. Two constraints are new, and both speak only of the break-glass
# event: it states one of its two actions, which no other event does, and it
# records no source address. The constraint that an actor is never the
# account, the indexes, and the trigger are left as they are.
#
# Reversing drops the MfaRecoveryRequest table, and with it any outstanding
# request. Reversing while rows with the new event types exist fails on the
# restored constraints and changes nothing, which is intended: those rows
# cannot be removed, and the earlier schema cannot represent them. An account
# whose session_epoch is above 0 has such a row, because only finalising a
# recovery raises it, so the column is never dropped while it is holding
# sessions ended.


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_password_reset"),
    ]

    operations = [
        migrations.CreateModel(
            name="MfaRecoveryRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="created at")),
            ],
            options={
                "verbose_name": "second-factor recovery request",
                "verbose_name_plural": "second-factor recovery requests",
            },
        ),
        migrations.RemoveConstraint(
            model_name="authenticationevent",
            name="accounts_authenticationevent_actor_iff_decision",
        ),
        migrations.RemoveConstraint(
            model_name="authenticationevent",
            name="accounts_authenticationevent_event_type_known",
        ),
        migrations.RemoveConstraint(
            model_name="authenticationevent",
            name="accounts_authenticationevent_user_known_unless_failure",
        ),
        migrations.AddField(
            model_name="authenticationevent",
            name="break_glass_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("revoke_device", "Lost device revoked"),
                    ("approve_enrollment", "Enrolment approved"),
                ],
                default="",
                max_length=20,
                verbose_name="break-glass action",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="session_epoch",
            field=models.PositiveIntegerField(default=0, verbose_name="session epoch"),
        ),
        migrations.AlterField(
            model_name="authenticationevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_success", "Signed in"),
                    ("login_failure", "Sign-in failed"),
                    ("logout", "Signed out"),
                    ("password_confirmation_failed", "Password not confirmed"),
                    ("mfa_challenge_issued", "Second factor requested"),
                    ("mfa_enrollment_started", "Second-factor enrolment started"),
                    ("mfa_enrollment_succeeded", "Second factor enrolled"),
                    ("mfa_verification_failed", "Second-factor code refused"),
                    ("mfa_verification_succeeded", "Second-factor code accepted"),
                    ("mfa_disabled", "Second factor disabled"),
                    ("mfa_enrollment_approved", "Second-factor enrolment approved"),
                    ("mfa_enrollment_rejected", "Second-factor enrolment rejected"),
                    ("mfa_device_replaced", "Second factor replaced"),
                    ("password_reset_requested", "Password reset requested"),
                    ("password_reset_succeeded", "Password reset"),
                    ("password_reset_failed", "Password reset refused"),
                    ("mfa_recovery_requested", "Second-factor recovery requested"),
                    ("mfa_recovery_failed", "Second-factor recovery request refused"),
                    ("mfa_recovery_rejected", "Second-factor recovery rejected"),
                    ("mfa_recovery_authorized", "Second-factor recovery authorised"),
                    ("mfa_recovery_completed", "Second-factor recovery completed"),
                    ("mfa_recovery_break_glass", "Second-factor recovery by break-glass"),
                ],
                max_length=32,
                verbose_name="event type",
            ),
        ),
        migrations.AddConstraint(
            model_name="authenticationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event_type__in",
                        [
                            "login_success",
                            "login_failure",
                            "logout",
                            "password_confirmation_failed",
                            "mfa_challenge_issued",
                            "mfa_enrollment_started",
                            "mfa_enrollment_succeeded",
                            "mfa_verification_failed",
                            "mfa_verification_succeeded",
                            "mfa_disabled",
                            "mfa_enrollment_approved",
                            "mfa_enrollment_rejected",
                            "mfa_device_replaced",
                            "password_reset_requested",
                            "password_reset_succeeded",
                            "password_reset_failed",
                            "mfa_recovery_requested",
                            "mfa_recovery_failed",
                            "mfa_recovery_rejected",
                            "mfa_recovery_authorized",
                            "mfa_recovery_completed",
                            "mfa_recovery_break_glass",
                        ],
                    )
                ),
                name="accounts_authenticationevent_event_type_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="authenticationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False),
                    (
                        "event_type__in",
                        (
                            "login_failure",
                            "password_reset_requested",
                            "password_reset_failed",
                            "mfa_recovery_failed",
                        ),
                    ),
                    _connector="OR",
                ),
                name="accounts_authenticationevent_user_known_unless_failure",
            ),
        ),
        migrations.AddConstraint(
            model_name="authenticationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("actor__isnull", False),
                        (
                            "event_type__in",
                            (
                                "mfa_enrollment_approved",
                                "mfa_enrollment_rejected",
                                "mfa_recovery_rejected",
                                "mfa_recovery_authorized",
                            ),
                        ),
                    ),
                    models.Q(
                        ("actor__isnull", True),
                        models.Q(
                            (
                                "event_type__in",
                                (
                                    "mfa_enrollment_approved",
                                    "mfa_enrollment_rejected",
                                    "mfa_recovery_rejected",
                                    "mfa_recovery_authorized",
                                ),
                            ),
                            _negated=True,
                        ),
                    ),
                    _connector="OR",
                ),
                name="accounts_authenticationevent_actor_iff_decision",
            ),
        ),
        migrations.AddConstraint(
            model_name="authenticationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("break_glass_action__in", ["revoke_device", "approve_enrollment"]),
                        ("event_type", "mfa_recovery_break_glass"),
                    ),
                    models.Q(
                        models.Q(("event_type", "mfa_recovery_break_glass"), _negated=True),
                        ("break_glass_action", ""),
                    ),
                    _connector="OR",
                ),
                name="accounts_authenticationevent_action_iff_break_glass",
            ),
        ),
        migrations.AddConstraint(
            model_name="authenticationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event_type", "mfa_recovery_break_glass"), _negated=True),
                    ("source_key", ""),
                    _connector="OR",
                ),
                name="accounts_authenticationevent_break_glass_has_no_source",
            ),
        ),
        migrations.AddField(
            model_name="mfarecoveryrequest",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
