# Generated by Django 5.2.17 on 2026-10-09 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# The general audit record (ADR-0018 points 27 to 48): AuditEvent and
# AuditEventChange. No existing table, column, constraint, or trigger is
# touched, and no row is written.
#
# Both tables are append-only, protected in the same way as RoleEvent,
# AuthenticationEvent, and AccountEvent (ADR-0012, migrations 0002, 0003, and
# 0006): one function and one trigger for each table, created here with the
# table so that it never exists unprotected, refuse UPDATE and DELETE on
# every row, for every database role. The same limits apply: TRUNCATE, and
# dropping or disabling a trigger, are matters of database privilege
# (ADR-0008).
#
# Reversing drops the triggers, their functions, and both tables. Unlike the
# reversal of a migration that only widened a constraint, nothing stops it
# when rows exist: reversing it on a database that holds audit events
# destroys them, and they cannot be rebuilt from anything else.
CREATE_AUDIT_EVENT_TRIGGER = """
CREATE FUNCTION accounts_auditevent_refuse_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'accounts_auditevent is append-only: % refused', TG_OP
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$;

CREATE TRIGGER accounts_auditevent_append_only
    BEFORE UPDATE OR DELETE ON accounts_auditevent
    FOR EACH ROW EXECUTE FUNCTION accounts_auditevent_refuse_change();
"""

DROP_AUDIT_EVENT_TRIGGER = """
DROP TRIGGER accounts_auditevent_append_only ON accounts_auditevent;
DROP FUNCTION accounts_auditevent_refuse_change();
"""

CREATE_AUDIT_EVENT_CHANGE_TRIGGER = """
CREATE FUNCTION accounts_auditeventchange_refuse_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'accounts_auditeventchange is append-only: % refused', TG_OP
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$;

CREATE TRIGGER accounts_auditeventchange_append_only
    BEFORE UPDATE OR DELETE ON accounts_auditeventchange
    FOR EACH ROW EXECUTE FUNCTION accounts_auditeventchange_refuse_change();
"""

DROP_AUDIT_EVENT_CHANGE_TRIGGER = """
DROP TRIGGER accounts_auditeventchange_append_only ON accounts_auditeventchange;
DROP FUNCTION accounts_auditeventchange_refuse_change();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_account_recovery_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deactivated", "Deactivated"),
                            ("reactivated", "Reactivated"),
                            ("marked_entered_in_error", "Marked as entered in error"),
                        ],
                        max_length=32,
                        verbose_name="action",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("registry.country", "Country"),
                            ("registry.language", "Language"),
                            ("registry.institution", "Institution"),
                            ("registry.institution_name", "Institution name"),
                        ],
                        max_length=32,
                        verbose_name="target type",
                    ),
                ),
                ("target_public_id", models.UUIDField(verbose_name="target public identifier")),
                (
                    "correlation_id",
                    models.CharField(blank=True, max_length=32, verbose_name="correlation ID"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit event",
                "verbose_name_plural": "audit events",
            },
        ),
        migrations.CreateModel(
            name="AuditEventChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("name_en", "English name"),
                            ("kind", "Kind"),
                            ("country", "Country"),
                            ("parent", "Parent"),
                            ("successor", "Successor"),
                            ("valid_from", "Valid from"),
                            ("valid_to", "Valid to"),
                        ],
                        max_length=32,
                        verbose_name="field",
                    ),
                ),
                (
                    "old_value",
                    models.CharField(blank=True, max_length=200, verbose_name="old value"),
                ),
                (
                    "new_value",
                    models.CharField(blank=True, max_length=200, verbose_name="new value"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="accounts.auditevent",
                        verbose_name="event",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit event change",
                "verbose_name_plural": "audit event changes",
            },
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "action__in",
                        [
                            "created",
                            "updated",
                            "deactivated",
                            "reactivated",
                            "marked_entered_in_error",
                        ],
                    )
                ),
                name="accounts_auditevent_action_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "target_type__in",
                        [
                            "registry.country",
                            "registry.language",
                            "registry.institution",
                            "registry.institution_name",
                        ],
                    )
                ),
                name="accounts_auditevent_target_type_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("action", "created"),
                        (
                            "target_type__in",
                            (
                                "registry.country",
                                "registry.language",
                                "registry.institution",
                                "registry.institution_name",
                            ),
                        ),
                    ),
                    models.Q(
                        ("action", "updated"),
                        (
                            "target_type__in",
                            (
                                "registry.country",
                                "registry.language",
                                "registry.institution",
                                "registry.institution_name",
                            ),
                        ),
                    ),
                    models.Q(
                        ("action", "deactivated"),
                        ("target_type__in", ("registry.country", "registry.language")),
                    ),
                    models.Q(
                        ("action", "reactivated"),
                        ("target_type__in", ("registry.country", "registry.language")),
                    ),
                    models.Q(
                        ("action", "marked_entered_in_error"),
                        ("target_type__in", ("registry.institution_name",)),
                    ),
                    _connector="OR",
                ),
                name="accounts_auditevent_action_fits_target_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditeventchange",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "field__in",
                        [
                            "name_en",
                            "kind",
                            "country",
                            "parent",
                            "successor",
                            "valid_from",
                            "valid_to",
                        ],
                    )
                ),
                name="accounts_auditeventchange_field_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditeventchange",
            constraint=models.CheckConstraint(
                condition=models.Q(("old_value", models.F("new_value")), _negated=True),
                name="accounts_auditeventchange_values_differ",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditeventchange",
            constraint=models.UniqueConstraint(
                fields=("event", "field"), name="accounts_auditeventchange_field_once_per_event"
            ),
        ),
        migrations.RunSQL(sql=CREATE_AUDIT_EVENT_TRIGGER, reverse_sql=DROP_AUDIT_EVENT_TRIGGER),
        migrations.RunSQL(
            sql=CREATE_AUDIT_EVENT_CHANGE_TRIGGER, reverse_sql=DROP_AUDIT_EVENT_CHANGE_TRIGGER
        ),
    ]
